### PR TITLE
feat(draw)/fix(checkWin): added check draw state logic & fixed checking

### LINKED ISSUE #2: No logic to calculate or handle draw state in the game
Currently, there is no logic in the backend to detect or handle a draw state when the game ends without a winner.

This is an essential part of the game logic to ensure fair results are communicated properly to both players, especially in cases where all board positions are filled and no one wins.

**Expected Solution:**
* The backend should return a "draw" value in the winner state when all board positions are filled and no player has won.
* The frontend will be responsible for handling this "draw" state by displaying the appropriate message to both players.

### PR DESCRIPTION
**Pull request by mahmoudalnkeeb**
- check the win state for each player
- check win state after new move or ability used
-  mark the game as started after both player joins the game

this resolves #2

### CODE REVIEW

**Comment by mahmoudalnkeeb** [comment]
@Moamal-2000 review the code and if you have any notes mention me in a comment I will merge the branch after your approval also I will keep the branch for future features and changes to the backend code also maybe I'll configure the deployment from it

File: server/classes/Game.js [hunk 1]
```diff
@@ -72,30 +72,59 @@ export class Game {
...
       [1, 0],
       [1, 1],
       [1, -1],
     ];
 
-    for (const [dr, dc] of directions) {
-      if (this.countAligned(row, col, dr, dc, symbol) >= size) {
-        this.isWinnerPopupVisible = true;
-        return true;
+    for (const symbol of [SYMBOL_X, SYMBOL_O]) {
```
Comment (Moamal-2000) [inline server/classes/Game.js:93]: @mahmoudalnkeeb the logic here is a bit hard to follow due to the deep nesting and the use of short variable names like c, r, dr, etc. I believe giving the variables more descriptive names would make it easier to read and understand.

Also, maybe there's a cleaner or simpler way to achieve the same purpose without too many nested conditions, just to make it more maintainable in the future. Thank you for your work

**Review by Moamal-2000 — APPROVED** [review]
Approved and merging for now since I know you're busy.

Just a heads-up, I left a comment on the symbol-checking logic (line R93). It works fine, but it's a bit hard to follow due to the deep nesting and short variable names like r, c, dr, etc.

If you get time later, consider refactoring it with clearer naming or a cleaner structure to improve readability and maintainability.
